### ISSUE TITLE
Bug on latest sketch

### ISSUE THREAD

**Issue by tijmenvangurp** [KimDal-hyeong/html-to-sketch-electron#13]
Hey I noticed that on the latest version of sketch: https://www.sketch.com/updates/#version-64 
the tool always (doesn't matter wich site) gives the same error.
![image](https://user-images.githubusercontent.com/9990026/77665642-3beb6100-6f80-11ea-9257-710c1475af7e.png)

Any idea what is causing this? hope you can fix it 👍🏻

**Comment by tijmenvangurp** [comment]
Seems to be a bug in the underlying plugin:
https://github.com/html-sketchapp/html-sketchapp/issues/191

**Comment by tijmenvangurp** [comment]
Seems we have to wait for this to be published

https://github.com/darknoon/sketchapp-json-plugin/issues/16

since the plugin https://github.com/html-sketchapp/html-sketchapp makes use of this other plugin

**Comment by KimDal-hyeong** [comment]
@tijmenvangurp 
Fixed it! Please test it in new version.🤩

**Comment by tijmenvangurp** [comment]
@KimDal-hyeong Hey sorry for my late reply :)

Everything works as it did before this, thanks a lot!
