### ISSUE TITLE
It does not work on 10.14.2

### ISSUE THREAD

**Issue by leminhhai** [KimDal-hyeong/html-to-sketch-electron#4]
Look like it does not work on macos 10.14.2 & sketch 52.5 (67469)
https://tppr.me/ripyA

**Comment by jaukia** [comment]
Creating manually "HTML to Sketch Electron" folder under "USER_FOLDER/Library/Application Support" fixed this for me.

**Comment by KimDal-hyeong** [comment]
I am sorry.😱
The problem was solved in v1.4.2.
Download : https://kimdal-hyeong.github.io/html-to-sketch-electron/download-analyst/
Thanks so much to @jaukia.😭
